-- MySQL Script generated by MySQL Workbench
-- Mon Jan 30 22:22:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante_delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante_delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante_delivery` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurante_delivery` ;

-- -----------------------------------------------------
-- Table `restaurante_delivery`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(20) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` INT(8) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_endereco` INT(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivel` TINYINT(1) NOT NULL,
  `data_inscricao` DATETIME NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `endereco_id_endereco`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_usuario_endereco_idx` (`endereco_id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_endereco`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `restaurante_delivery`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
