-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 09:14:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante_delivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante_delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante_delivery` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurante_delivery` ;

-- -----------------------------------------------------
-- Table `restaurante_delivery`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(20) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` INT(8) NOT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_carrinho` INT(11) NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `numero_pedido` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`carrinho` (
  `id_carrinho` INT NOT NULL AUTO_INCREMENT,
  `status` INT(1) NOT NULL,
  `valor_carrinho` DECIMAL(10,2) UNSIGNED NOT NULL,
  `valor_taxa` DECIMAL(10,2) UNSIGNED NOT NULL,
  `valor_desconto` DECIMAL(10,2) UNSIGNED NOT NULL,
  `data_criacao` DATETIME NOT NULL DEFAULT 1900-01-01 00:00:00,
  `data_atualizacao` DATETIME NOT NULL DEFAULT 1900-01-01 00:00:00,
  `id_usuario` INT(11) NOT NULL,
  `pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_carrinho`),
  INDEX `fk_carrinho_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `restaurante_delivery`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_endereco` INT(11) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nivel` TINYINT(1) NOT NULL,
  `data_inscricao` DATETIME NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  `carrinho_id_carrinho` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `endereco_id_endereco`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_usuario_endereco_idx` (`endereco_id_endereco` ASC) VISIBLE,
  INDEX `fk_usuario_carrinho1_idx` (`carrinho_id_carrinho` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_endereco`
    FOREIGN KEY (`endereco_id_endereco`)
    REFERENCES `restaurante_delivery`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_carrinho1`
    FOREIGN KEY (`carrinho_id_carrinho`)
    REFERENCES `restaurante_delivery`.`carrinho` (`id_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nome_nivel` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(255) NOT NULL,
  `cnpj` INT(14) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `logradouro` VARCHAR(20) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` INT(8) NOT NULL,
  `data_inscricao` DATETIME NOT NULL,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`produto_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`produto_tipo` (
  `id_produto_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome_produto_tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_produto_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`produto_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`produto_categoria` (
  `id_categoria_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria_tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_categoria_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`promocao` (
  `id_promocao` INT NOT NULL AUTO_INCREMENT,
  `nome_promocao` VARCHAR(100) NOT NULL,
  `desconto` INT(2) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  PRIMARY KEY (`id_promocao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`promocao_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`promocao_produto` (
  `id_promocao_produto` INT NOT NULL AUTO_INCREMENT,
  `id_promocao` INT(11) UNSIGNED NOT NULL,
  `promocao_id_promocao` INT NOT NULL,
  PRIMARY KEY (`id_promocao_produto`),
  INDEX `fk_promocao_produto_promocao1_idx` (`promocao_id_promocao` ASC) VISIBLE,
  CONSTRAINT `fk_promocao_produto_promocao1`
    FOREIGN KEY (`promocao_id_promocao`)
    REFERENCES `restaurante_delivery`.`promocao` (`id_promocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`item_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`item_carrinho` (
  `id_item_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_carrinho` INT(11) NOT NULL,
  `id_produto` INT(11) NOT NULL,
  `valor_desconto` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `quantidade_produto` INT(3) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_item_carrinho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `id_fornecedor` INT(11) NOT NULL,
  `id_produto_categoria` INT(11) NOT NULL,
  `id_produto_tipo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `estoque` INT(11) UNSIGNED NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,2) UNSIGNED NOT NULL,
  `fornecedor_id_fornecedor` INT NOT NULL,
  `produto_tipo_id_produto_tipo` INT NOT NULL,
  `produto_categoria_id_categoria_tipo` INT NOT NULL,
  `promocao_produto_id_promocao_produto` INT NOT NULL,
  `item_carrinho_id_item_carrinho` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `promocao_produto_id_promocao_produto`),
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_id_fornecedor` ASC) VISIBLE,
  INDEX `fk_produto_produto_tipo1_idx` (`produto_tipo_id_produto_tipo` ASC) VISIBLE,
  INDEX `fk_produto_produto_categoria1_idx` (`produto_categoria_id_categoria_tipo` ASC) VISIBLE,
  INDEX `fk_produto_promocao_produto1_idx` (`promocao_produto_id_promocao_produto` ASC) VISIBLE,
  INDEX `fk_produto_item_carrinho1_idx` (`item_carrinho_id_item_carrinho` ASC) VISIBLE,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id_fornecedor`)
    REFERENCES `restaurante_delivery`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_produto_tipo1`
    FOREIGN KEY (`produto_tipo_id_produto_tipo`)
    REFERENCES `restaurante_delivery`.`produto_tipo` (`id_produto_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_produto_categoria1`
    FOREIGN KEY (`produto_categoria_id_categoria_tipo`)
    REFERENCES `restaurante_delivery`.`produto_categoria` (`id_categoria_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_promocao_produto1`
    FOREIGN KEY (`promocao_produto_id_promocao_produto`)
    REFERENCES `restaurante_delivery`.`promocao_produto` (`id_promocao_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_item_carrinho1`
    FOREIGN KEY (`item_carrinho_id_item_carrinho`)
    REFERENCES `restaurante_delivery`.`item_carrinho` (`id_item_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(80) NOT NULL,
  `faixa_salarial` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_delivery`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_delivery`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` INT(14) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `logradouro` VARCHAR(20) NOT NULL,
  `numero` INT(11) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cep` INT(8) NOT NULL,
  `data_inscricao` DATETIME NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cargo` INT(11) NOT NULL,
  `cargo_id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`, `cargo_id_cargo`),
  INDEX `fk_funcionario_cargo1_idx` (`cargo_id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_id_cargo`)
    REFERENCES `restaurante_delivery`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
